### ISSUE TITLE
Errors are not being propogated to the console

### ISSUE THREAD

**Issue by jsvazic** [Axonify/muffin.io#1]
When an error occurs during the compilation process, an ERROR notice is given on the output, but no error code is returned thus causing a problem with the Ant exec call since it is not causing the task to fail due to no error code apparently being returned.

**Comment by ylian** [comment]
I can fix it but you may need to change some permissions for me. I think I opted out of the organization a couple of weeks ago and lost write permission to this repo. (GitHub kept sending me commits update from you guys even though I should only see activities for this one repo.)

Also I have successfully secured an organization account for muffin. Check it out here: github.com/muffin

**Comment by jsvazic** [comment]
Done!  You should have push/pull rights now.

**Comment by ylian** [comment]
Thanks! Will fix shortly.

**Comment by cddoherty** [comment]
John,  why would I have gotten this message as well?

_From:_ John Svazic [mailto:notifications@github.com]
_Sent:_ June-26-13 10:14 AM
_To:_ Axonify/muffin.io
_Subject:_ [muffin.io] Errors are not being propogated to the console (#1)

When an error occurs during the compilation process, an ERROR notice is
given on the output, but no error code is returned thus causing a problem
with the Ant exec call since it is not causing the task to fail due to no
error code apparently being returned.

—
Reply to this email directly or view it on
GitHubhttps://github.com/Axonify/muffin.io/issues/1
.[image: Image removed by sender.]

## 

*This email and any attachments are confidential and are intended only for 
the person(s) to whom it is addressed.  If you are not the designated 
recipient, please notify the sender immediately, and delete the original 
and any copies. Any use of the message by you is prohibited. *

**Comment by ylian** [comment]
John, can you post some error logs? I tried with a broken build, and the error code is 1.

```
16:20:42 [INFO]: Building project...
16:20:42 [INFO]: compiled /Users/ylian/workspace/HappenTransit/client/config.coffee
16:20:42 [ERROR]: include_module_loader is not defined

Meerkat:HappenTransit ylian$ echo $?
1
```

**Comment by jsvazic** [comment]
That's odd.  I'm calling it from an Ant exec task with the failonerror property set to true, so I would expect a non-zero error code to fail the build.  I may be wrong though...  Let me dig into it on my side a bit more.  The problem is that the Maven build (which calls the Ant exec task) isn't stopping.  I'll do some further investigation here and let you know.

**Comment by ylian** [comment]
Ha! I think I reproduced it. It happens on `muffin minify`, but not on `muffin build`. Clearly error code from a child_process isn't passed to the parent process. Fixing.

```
Meerkat:HappenTransit ylian$ muffin minify
16:33:09 [INFO]: Preparing project files for production...
16:33:10 [INFO]: 16:33:10 [INFO]: Building project...

16:33:10 [INFO]: 16:33:10 [INFO]: compiled /Users/ylian/workspace/HappenTransit/client/config.coffee

16:33:10 [ERROR]: 16:33:10 [ERROR]: include_module_loader is not defined


Meerkat:HappenTransit ylian$ echo $?
0
```

**Comment by ylian** [comment]
John, can you rebuild muffin from the master branch? Try it and let me know if the issue is fixed.

**Comment by jsvazic** [comment]
Yep, this build works perfectly!  Thanks Yaogang!

**Comment by ylian** [comment]
Cool. I will bump up the patch version number and push to npm.

**Comment by ylian** [comment]
Bumped up version to 0.1.4 and pushed to npm.

**Comment by jsvazic** [comment]
Awesome, thanks for the quick turnaround Yaogang.  :-)
